package com.randallengineering.jokarztimeclock.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance
import com.randallengineering.jokarztimeclock.data.models.ThemeMode
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The live timer is drawn in `onSurface` on a `surfaceContainerHighest` plate. Every built-in
 * palette (and the pre-Android-12 DYNAMIC fallback, light and dark) must keep that pair at WCAG AAA
 * contrast (7:1), so a palette tweak can never make the most important number on screen hard to read.
 * Wallpaper palettes are generated by the system to M3 tone rules and are not testable here.
 */
class TimerContrastTest {

    @Test
    fun timerTextMeetsAaaContrastOnItsPlateInEveryPreset() {
        val failures = mutableListOf<String>()
        for (mode in ThemeMode.values()) for (dark in listOf(false, true)) {
            val scheme = presetColorScheme(mode, dark)
            val ratio = contrast(scheme.onSurface, scheme.surfaceContainerHighest)
            if (ratio < 7.0) failures += "$mode dark=$dark: %.2f:1".format(ratio)
        }
        assertTrue("Timer contrast below 7:1 — ${failures.joinToString()}", failures.isEmpty())
    }

    private fun contrast(a: Color, b: Color): Double {
        val la = a.luminance().toDouble()
        val lb = b.luminance().toDouble()
        return (maxOf(la, lb) + 0.05) / (minOf(la, lb) + 0.05)
    }
}
